name = "MLiSRegistry"
uuid = "25a7db02-d7a1-43fe-83c9-5e63afd352aa"
repo = "git@github.com:MLiS-Research/MLiSRegistry.jl.git"

[packages]
0f07a834-652b-47c2-8205-950502167029 = { name = "SimpleNNs", path = "S/SimpleNNs" }
90a4db8d-a042-44ed-af16-fb847fa05318 = { name = "TransitionPathSampling", path = "T/TransitionPathSampling" }
